### ISSUE TITLE
max_concurrent_tasks not applicable in non-partitioned z-order

### ISSUE THREAD

**Issue by marsupialtail** [delta-io/delta-rs#1656]
# Environment

**Delta-rs version**: 0.10.2

**Binding**: Python

**Environment**:
Ubuntu 22:

***
# Bug

see title.

**Comment by marsupialtail** [comment]
@wjones127

**Comment by wjones127** [comment]
In order to fix this, we need to pass down a memory limit to DataFusion. Also we might want to consider passing down a limit on the number of threads used, though perhaps a memory limit is sufficient.

**Comment by edgBR** [comment]
Hi,

I have noticed this recently. Changing this parameter doesn't have any impact in performance. In fact even using a larger compute to run z order seems to not decrease the time that z order consumes.

**Comment by obiii** [comment]
Hi,

I've had similar findings—the parameter seems to have no impact on performance. I’d be grateful if this could be looked into soon; the issue is almost like an old friend at this point!

**Comment by carlos6moya** [comment]
Hi, 

I am conducting various tests in AWS to improve the performance of the Z-order operation. I performed a Z-order operation using Fargate with 16 vCPUs and 120 GB of memory, but the runtime was the same as when using SageMaker on AWS with 96 vCPUs and 768 GB of RAM.

Additionally, I adjusted the maximum concurrency settings, but the execution time remained unchanged.

**Comment by ion-elgreco** [comment]
I guess you are all on same team, would be useful if any of you provides stats about your table.

The streams are created per BIN of files, so if there aren't many bins there is no point in increasing the max concurrent tasks

**Comment by edgBR** [comment]
Hi @ion-elgreco,

@justkr and @obiii and I work on the same team. Currently we have 2 projects in production running:

deltalake==0.19.2

and 

deltalake==0.19.2

Respectively, both of them run AzureML workloads using as base docker image:

mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04

However I detected this problem in the last project. Which dependencies are as follows:

```
channels:
  - defaults
dependencies:
  - python=3.10.14
  - pip:
      - numpy==1.26.4
      - pandera==0.20.4
      - pandas==2.2.2
      - polars==1.10.0
      - pyarrow==17.0.0
      - deltalake==0.19.2
      - mltable==1.6.1
      - tsfeatures==0.4.5
      - holidays==0.58
      - scikit-learn==1.5.1
      - azure-ai-ml==1.21.0
      - azure-core==1.31.0
      - azure-identity==1.9.0
      - azure.keyvault==4.2.0
  - conda:
      - conda=23.3.0
```

We are using azureML environments but as mentioned above the base image is: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04

Currently we have 2 modes of loading data in our delta tables:

- Full load: that means we fetch all of the data from our transactional system.
- Incremental load: we fetch just the new records.
- Ad-hoc: this is an special workload that is not yet ready for production as we are optimizing it, more details below.

For the full load and incremental load workloads the statistics are as follows:

bronze: 11523107 rows
silver: 2008737 rows
gold monthly table: 1479060 rows
gold daily table:  8559852

Our underlying parquet files are around 50MBs (not the optimum size but we are using zstd compression, we have not decided yet in how to handle this).

Currently our processing jobs take around 2m 40s in a Standard_F32s_v2 (32 cores, 64 GB RAM, 256 GB disk) machine. 

For the ad-hoc workloads the details of the table are as follows:

bronze table 1: 1460M rows (approx) / 6 columns
bronze table 2: 365 M rows (approx) / 23 columns.
silver table: around 2.6B rows / 29 columns
gold table: 42 M rows  (approx)/ 40 columns

Runtime:  approx 15mins in Standard_FX48mds (48 cores, 1008 GB RAM, 2016 GB disk) .

Currently we would like to understand which parameters affect the Z order performance and clarify the usage of max_concurrent_tasks as well as max_spill_size.

BR
E
