### ISSUE TITLE
min & max values are wrong when writing `Date32` dtype

### ISSUE THREAD

**Issue by universalmind303** [delta-io/delta-rs#1670]
# Environment

**Delta-rs version**:
```toml
[dependencies]
datafusion = "31.0.0"
tokio = { version = "1.32.0", features = ["rt-multi-thread"] }

[dependencies.deltalake]
git = "https://github.com/delta-io/delta-rs.git"
rev = "93eb9cefba67fcb91ba99eb9cbc7874f089303bb"
features = ["s3", "gcs", "azure", "datafusion", "arrow", "parquet"]
```
**Binding**: 
rust 

**Environment**:
- **Cloud provider**:
- **OS**:
- **Other**:

***
# Bug

**What happened**:
datafusion predicate pushdowns fail for `Date` parquet datatype

**What you expected to happen**:
result set is not empty & the predicate is properly applied

**How to reproduce it**:
fully reproducible example here 
https://github.com/GlareDB/glaredb/issues/1834

simplified example here
```rust
use datafusion::prelude::SessionContext;
use std::sync::Arc;

#[tokio::main]
async fn main() {
    let mut ctx = SessionContext::new();
    // assuming the lineitem dataset as created from parquet
    let table = deltalake::open_table("./lineitems/").await.unwrap();
    println!("{:?}", table);
    ctx.register_table("lineitem", Arc::new(table)).unwrap();

    let batches = ctx
        .sql("SELECT * FROM lineitem where l_shipdate > date '1995-03-09';")
        .await
        .unwrap()
        .collect()
        .await
        .unwrap();
    println!("batches {:?}", batches)
}
```
**More details**:

the datafusion plan shows that the predicate is getting pushed down to delta exec

```sql
explain SELECT l_shipdate FROM lineitem2 where l_shipdate = date '1995-03-09';
```

It actually looks like the file groups are empty? 
```
    CoalesceBatchesExec: target_batch_size=8192
      RepartitionExec: partitioning=UnknownPartitioning(1), input_partitions=0
        LocalLimitExec: fetch=1
          CoalesceBatchesExec: target_batch_size=8192
            FilterExec: l_shipdate@0 = 9198
              ParquetExec: 
                file_groups={0 groups: []}, 
                projection=[l_shipdate], 
                predicate=l_shipdate@10 = 9198, 
                pruning_predicate=l_shipdate_min@0 <= 9198 AND 9198 <= l_shipdate_max@1
```

the same query on parquet returns the proper file groups
```
    CoalescePartitionsExec
      CoalesceBatchesExec: target_batch_size=8192
        FilterExec: l_shipdate@0 = 9198
          ParquetExec: 
            file_groups={12 groups: [
                [....lineitem/00.parquet:0..22567114], 
                [....lineitem/00.parquet:22567114..45134228], 
                [....lineitem/00.parquet:45134228..67701342], 
                [....lineitem/00.parquet:67701342..90268456], 
                [....lineitem/00.parquet:90268456..112835570], 
                ...
            
            ]}, 
            projection=[l_shipdate], 
            predicate=l_shipdate@10 = 9198, 
            pruning_predicate=l_shipdate_min@0 <= 9198 AND 9198 <= l_shipdate_max@1
```
