### ISSUE TITLE
trying to access table in s3 hangs forever with current_thread runtime flavor

### ISSUE THREAD

**Issue by swanandx** [delta-io/delta-rs#3336]
# Environment

**Delta-rs version**:  0.25

**Binding**: Rust

**Environment**:
- **Cloud provider**: AWS
- **OS**: MacOS
- **Other**: -

***
# Bug

**What happened**: 

When trying to create / open table at s3 with uri like `s3://mybucket` it hangs forever

**What you expected to happen**:

It should resolve successfully or throw appropriate error

**How to reproduce it**:

Cargo.toml
```toml
deltalake = { version = "0.25", features = ["datafusion", "s3"] }
tokio = { version = "1.43.0", features = ["full"] }
```

poc
```rust
// using multi_thread flavor works as expected!
// #[tokio::main(flavor = "multi_thread")]
#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), deltalake::errors::DeltaTableError> {
    deltalake::aws::register_handlers(None);
    let mut ops = deltalake::DeltaOps::try_from_uri("s3://mybucket").await?;
    println!("current_thread runtime flavor never reaches here");

    Ok(())
}
```

**More details**:

There was similar issue #2590 but not sure what is causing this.
